{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dxfeedframework\/promise\/getexception()"]}],"sections":[],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"DXFeedFramework"}],"externalID":"s:15DXFeedFramework7PromiseC12getExceptionAA05GraalE0OSgyF","role":"symbol","title":"getException()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getException","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"GraalException","preciseIdentifier":"s:15DXFeedFramework14GraalExceptionO"},{"kind":"text","text":"?"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Returns exceptional outcome of computation. If computation has no  "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/hasException()"},{"text":" exception,","type":"text"},{"type":"text","text":" "},{"text":"then this method returns nil. If computation has completed exceptionally or was cancelled, then","type":"text"},{"text":" ","type":"text"},{"text":"the result of this method is not nil.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If computation was "},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/isCancelled()","type":"reference","isActive":true},{"type":"text","text":" cancelled, then this method returns an"},{"type":"text","text":" "},{"text":"instance of GraalException.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getException"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:15DXFeedFramework14GraalExceptionO","text":"GraalException","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/GraalException"},{"text":"?","kind":"text"}]}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"GraalException. Rethrows exception from Java."}]}]}],"identifier":{"url":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/getException()","interfaceLanguage":"swift"},"references":{"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Promise/getException()":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Returns exceptional outcome of computation. If computation has no  "},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/hasException()","type":"reference","isActive":true},{"text":" exception,","type":"text"},{"text":" ","type":"text"},{"text":"then this method returns nil. If computation has completed exceptionally or was cancelled, then","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the result of this method is not nil."},{"type":"text","text":" "},{"type":"text","text":"If computation was "},{"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/isCancelled()","isActive":true},{"text":" cancelled, then this method returns an","type":"text"},{"type":"text","text":" "},{"text":"instance of GraalException.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getException","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:15DXFeedFramework14GraalExceptionO","text":"GraalException","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/dxfeedframework\/promise\/getexception()","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/getException()","title":"getException()","type":"topic"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/GraalException":{"abstract":[{"type":"text","text":"Represents errors that occur when calling graal function."}],"type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/GraalException","title":"GraalException","url":"\/documentation\/dxfeedframework\/graalexception","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GraalException"}],"navigatorTitle":[{"text":"GraalException","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Promise/isCancelled()":{"kind":"symbol","role":"symbol","abstract":[{"text":"Returns ","type":"text"},{"inlineContent":[{"type":"text","text":"true"}],"type":"strong"},{"type":"text","text":" when computation was canceled."},{"type":"text","text":" "},{"type":"text","text":"Use "},{"isActive":true,"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/getException()","type":"reference"},{"type":"text","text":" method to get the corresponding exception."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isCancelled","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/dxfeedframework\/promise\/iscancelled()","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/isCancelled()","title":"isCancelled()","type":"topic"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework":{"title":"DXFeedFramework","abstract":[],"url":"\/documentation\/dxfeedframework","type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework","role":"collection","kind":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Promise":{"url":"\/documentation\/dxfeedframework\/promise","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Promise"}],"navigatorTitle":[{"text":"Promise","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise","title":"Promise","abstract":[{"type":"text","text":"Result of a computation that will be completed normally or exceptionally in the future."},{"text":" ","type":"text"},{"type":"text","text":"This class is designed to represent a promise to deliver certain result."}],"role":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Promise/hasException()":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Returns "},{"inlineContent":[{"type":"text","text":"true"}],"type":"strong"},{"text":" when computation has completed exceptionally or was cancelled.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Use "},{"isActive":true,"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/getException()","type":"reference"},{"type":"text","text":" method to get the exceptional outcome of the computation."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"hasException","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/dxfeedframework\/promise\/hasexception()","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/hasException()","title":"hasException()","type":"topic"}}}